env:
  - FDB_VERSION="5.1.7"
addons:
  apt:
    packages:
      - build-essential
before_install:
  - |
    if [ $TRAVIS_OS_NAME = linux ]; then
      wget "https://www.foundationdb.org/downloads/$FDB_VERSION/ubuntu/installers/foundationdb-clients_$FDB_VERSION-1_amd64.deb"
      sudo dpkg -i "foundationdb-clients_$FDB_VERSION-1_amd64.deb"
      wget "https://www.foundationdb.org/downloads/$FDB_VERSION/ubuntu/installers/foundationdb-server_$FDB_VERSION-1_amd64.deb"
      sudo dpkg -i "foundationdb-server_$FDB_VERSION-1_amd64.deb"
    else
      brew install elixir
      wget "https://www.foundationdb.org/downloads/$FDB_VERSION/macOS/installers/FoundationDB-$FDB_VERSION.pkg"
      sudo installer -pkg "FoundationDB-$FDB_VERSION.pkg" -target /
      mix local.rebar --force
      mix local.hex --force
      mix deps.get
    fi

matrix:
  include:
    - language: elixir
      otp_release: 19.3
      elixir: 1.5
      os: linux
    - language: elixir
      otp_release: 20.3
      elixir: 1.5
      os: linux
    - language: elixir
      otp_release: 20.3
      elixir: 1.6
      os: linux
      env: BINDINGS_TEST=true FDB_VERSION="5.1.7"
    - os: osx

script:
  - make
  - mix test --trace --include integration
  - |
    if [ "$BINDINGS_TEST" = "true" ]; then
      curl -L "https://github.com/apple/foundationdb/archive/$FDB_VERSION.tar.gz" > foundation.tar.gz
      tar -xvf foundation.tar.gz
      rm foundation.tar.gz
      mv foundationdb* foundationdb
      cd foundationdb
      patch -p1 < ../test/foundationdb.patch
      cd ..
      ./test/loop.sh
    fi
